baseurl = "https://phillipwoolley.netlify.com/"
languageCode = "en-US"
title = "Phillip Woolley"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "headshot.png"
  author = "Phillip Woolley"
  description = "A website with my Computational Biology Projects and Blogs!"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "prwoolley"
  Email         = "prwoolley@utexas.edu"


## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"





